// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcl5sw6uJjIFjD9GfHGYLNyynQnazAe9E',
    appId: '1:1024170805599:web:ddd1c51a8f67ea56be0eea',
    messagingSenderId: '1024170805599',
    projectId: 'classtic-47654',
    authDomain: 'classtic-47654.firebaseapp.com',
    storageBucket: 'classtic-47654.firebasestorage.app',
    measurementId: 'G-1SSW7BTQ44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClu9rNcNgIWljRiAzuEnvuMKoXFUYSU2k',
    appId: '1:1024170805599:android:87fc86ce5727afa4be0eea',
    messagingSenderId: '1024170805599',
    projectId: 'classtic-47654',
    storageBucket: 'classtic-47654.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3JaYNve4r1IMrtOhtNSJ62LqvfjT9wSI',
    appId: '1:1024170805599:ios:5b8707da99c03c65be0eea',
    messagingSenderId: '1024170805599',
    projectId: 'classtic-47654',
    storageBucket: 'classtic-47654.firebasestorage.app',
    iosBundleId: 'com.example.classtic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3JaYNve4r1IMrtOhtNSJ62LqvfjT9wSI',
    appId: '1:1024170805599:ios:5b8707da99c03c65be0eea',
    messagingSenderId: '1024170805599',
    projectId: 'classtic-47654',
    storageBucket: 'classtic-47654.firebasestorage.app',
    iosBundleId: 'com.example.classtic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcl5sw6uJjIFjD9GfHGYLNyynQnazAe9E',
    appId: '1:1024170805599:web:3692cd14c9b79248be0eea',
    messagingSenderId: '1024170805599',
    projectId: 'classtic-47654',
    authDomain: 'classtic-47654.firebaseapp.com',
    storageBucket: 'classtic-47654.firebasestorage.app',
    measurementId: 'G-93J2JD9XVN',
  );
}
